import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    backgroundColor: '#3b82f6',
    padding: 16,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  headerText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#f8fafc',
  },
  versionText: {
    fontSize: 12,
    color: '#f8fafc',
    opacity: 0.8,
    marginTop: 4,
  },

  // Home Screen Styles
  homeContainer: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },

  // Greeting Section (Top)
  greetingSection: {
    padding: 20,
    paddingTop: 24,
  },
  greetingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  greetingText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 8,
  },
  dateText: {
    fontSize: 16,
    color: '#64748b',
    marginBottom: 16,
  },
  divider: {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginVertical: 16,
  },
  motivationalText: {
    fontSize: 16,
    color: '#475569',
    fontStyle: 'italic',
    lineHeight: 24,
  },

  // Chat Section (Middle)
  chatSection: {
    padding: 20,
    paddingTop: 8,
  },
  chatCard: {
    backgroundColor: '#3b82f6',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
    minHeight: 240,
    justifyContent: 'center',
  },
  chatIconContainer: {
    marginBottom: 16,
  },
  chatIcon: {
    fontSize: 64,
  },
  chatTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 8,
    textAlign: 'center',
  },
  chatSubtitle: {
    fontSize: 16,
    color: '#e0e7ff',
    marginBottom: 24,
    textAlign: 'center',
  },
  chatButton: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 24,
  },
  chatButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3b82f6',
  },

  // Games Section (Bottom)
  gamesSection: {
    padding: 20,
    paddingTop: 8,
    paddingBottom: 32,
  },
  gamesSectionTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 8,
  },
  gamesSectionSubtitle: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 16,
  },
  gamesScrollContainer: {
    paddingVertical: 8,
  },
  gameCard: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 20,
    marginRight: 16,
    width: 160,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  gameIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  gameTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: 8,
  },
  gameDescription: {
    fontSize: 13,
    color: '#64748b',
    lineHeight: 18,
  },

  // Mini Games Screen
  miniGamesContainer: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  gamesListHeader: {
    padding: 20,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  gamesListTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#0f172a',
    marginBottom: 8,
  },
  gamesListSubtitle: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
  },
  gameListCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  gameListIconContainer: {
    marginRight: 16,
  },
  gameListIcon: {
    fontSize: 48,
  },
  gameListContent: {
    flex: 1,
  },
  gameListTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: 4,
  },
  gameListDescription: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 20,
  },
  gameListArrow: {
    fontSize: 24,
    color: '#cbd5e1',
    marginLeft: 8,
  },
  comingSoonBadgeSmall: {
    backgroundColor: '#fef3c7',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    marginTop: 8,
  },
  comingSoonBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400e',
  },

  // Game Detail View
  gameDetailContainer: {
    flex: 1,
  },
  gameDetailHeader: {
    padding: 32,
    alignItems: 'center',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  gameDetailIcon: {
    fontSize: 80,
    marginBottom: 16,
  },
  gameDetailTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  gameDetailContent: {
    padding: 24,
  },
  gameDetailDescription: {
    fontSize: 16,
    color: '#475569',
    lineHeight: 24,
    marginBottom: 24,
  },
  playButton: {
    backgroundColor: '#3b82f6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  playButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
  },
  comingSoonContainer: {
    backgroundColor: '#fef3c7',
    padding: 20,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: 'center',
  },
  comingSoonBadge: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#92400e',
    marginBottom: 8,
  },
  comingSoonText: {
    fontSize: 14,
    color: '#78350f',
    textAlign: 'center',
  },
  backToGamesButton: {
    padding: 12,
    alignItems: 'center',
  },
  backToGamesButtonText: {
    fontSize: 16,
    color: '#3b82f6',
    fontWeight: '500',
  },

  // Figma Design Styles
  figmaHomeContainer: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },

  // Figma Greeting Section
  figmaGreetingSection: {
    padding: 16,
    paddingTop: 64,
    alignItems: 'center',
    gap: 16,
  },
  figmaGreetingText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    textAlign: 'center',
  },
  figmaSubtitle: {
    fontSize: 16,
    color: '#4b5563',
    textAlign: 'center',
  },

  // Figma Button Row
  figmaButtonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 24,
    marginTop: 16,
    paddingHorizontal: 16,
  },
  figmaButton: {
    flexDirection: 'row',
    backgroundColor: '#171717',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    minHeight: 36,
    alignItems: 'center',
    gap: 8,
  },
  figmaButtonIcon: {
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  figmaButtonIconText: {
    fontSize: 12,
  },
  figmaButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#ffffff',
  },

  // Figma Chat Preview
  figmaChatPreviewContainer: {
    marginHorizontal: 16,
    marginTop: 32,
  },
  figmaChatPreview: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 16,
  },
  figmaChatMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
  },
  figmaChatMessageRowRight: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    gap: 16,
  },
  figmaAvatarLeft: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  figmaAvatarRight: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  figmaAvatarText: {
    fontSize: 20,
  },
  figmaChatBubbleLeft: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 12,
    paddingHorizontal: 16,
    shadowColor: '#d4d4d4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  figmaChatBubbleRight: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 12,
    paddingHorizontal: 16,
    shadowColor: '#d4d4d4',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#737373',
    maxWidth: '70%',
  },
  figmaChatBubbleText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
  },
  figmaChatBubbleTextRight: {
    fontSize: 14,
    fontWeight: '500',
    color: '#111827',
  },
  figmaChatPreviewTap: {
    marginTop: 8,
    padding: 8,
    alignItems: 'center',
  },
  figmaChatPreviewTapText: {
    fontSize: 12,
    color: '#6b7280',
    fontStyle: 'italic',
  },

  // Figma Games Section
  figmaGamesContainer: {
    marginTop: 32,
    marginHorizontal: 16,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    paddingBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginBottom: 32,
  },
  figmaGamesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 16,
  },
  figmaGamesIconContainer: {
    width: 48,
    height: 48,
    backgroundColor: '#eef2ff',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  figmaGamesIcon: {
    fontSize: 24,
  },
  figmaGamesTitle: {
    fontSize: 18,
    color: '#111827',
  },
  figmaGamesScrollContainer: {
    gap: 16,
    paddingBottom: 8,
  },
  figmaGameCard: {
    width: 280,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  figmaGameIcon: {
    width: 56,
    height: 64,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#ffffff',
  },
  figmaGameIconInner: {
    width: 56,
    height: 56,
    borderRadius: 12,
    position: 'absolute',
  },
  figmaGameContent: {
    flex: 1,
    justifyContent: 'center',
  },
  figmaGameTitle: {
    fontSize: 12,
    fontWeight: '500',
    color: '#000000',
    marginBottom: 4,
  },
  figmaGameDescription: {
    fontSize: 12,
    fontWeight: '500',
    color: '#000000',
    lineHeight: 16,
  },

  // Figma Chat Screen Styles
  figmaChatContainer: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  figmaChatHeader: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  figmaChatHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    height: 48,
  },
  figmaChatAvatar: {
    width: 40,
    height: 40,
    borderRadius: 32,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff',
    overflow: 'hidden',
  },
  figmaChatAvatarText: {
    fontSize: 24,
  },
  figmaChatHeaderText: {
    flex: 1,
  },
  figmaChatTitle: {
    fontSize: 18,
    fontWeight: '400',
    color: '#111827',
    lineHeight: 28,
    marginTop: -4,
  },
  figmaChatSubtitle: {
    fontSize: 14,
    fontWeight: '400',
    color: '#4b5563',
    lineHeight: 20,
    marginTop: -6,
  },
  figmaChatMessagesArea: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  figmaChatMessagesList: {
    padding: 24,
    flexGrow: 1,
  },
  figmaChatEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 96,
  },
  figmaChatEmptyText: {
    fontSize: 16,
    color: '#64748b',
  },
  figmaChatUserMessageContainer: {
    alignSelf: 'flex-end',
    marginBottom: 12,
    maxWidth: '75%',
  },
  figmaChatAiMessageContainer: {
    alignSelf: 'flex-start',
    marginBottom: 12,
    maxWidth: '75%',
  },
  figmaChatUserMessage: {
    backgroundColor: '#4f46e5',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
  },
  figmaChatAiMessage: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  figmaChatUserMessageText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#ffffff',
    lineHeight: 24,
    marginTop: -7,
  },
  figmaChatAiMessageText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#111827',
    lineHeight: 24,
    marginTop: -7,
  },
  figmaChatUserTimestamp: {
    fontSize: 12,
    fontWeight: '400',
    color: '#c7d2fe',
    lineHeight: 16,
    marginTop: 8,
  },
  figmaChatAiTimestamp: {
    fontSize: 12,
    fontWeight: '400',
    color: '#6b7280',
    lineHeight: 16,
    marginTop: 8,
  },
  figmaChatInputContainer: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  figmaChatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    height: 48,
  },
  figmaChatInput: {
    flex: 1,
    backgroundColor: '#f9fafb',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    fontWeight: '400',
    color: '#111827',
    borderWidth: 1,
    borderColor: '#d1d5db',
    height: 48,
  },
  figmaChatInputPlaceholder: {
    color: '#6b7280',
  },
  figmaChatSendButton: {
    width: 48,
    height: 48,
    backgroundColor: '#22c55e',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  figmaChatSendButtonDisabled: {
    opacity: 0.5,
  },
  figmaChatSendIcon: {
    fontSize: 20,
  },
  figmaChatLoadingContainer: {
    paddingHorizontal: 24,
    paddingVertical: 8,
  },
  figmaChatLoadingText: {
    fontSize: 14,
    color: '#6b7280',
    fontStyle: 'italic',
  },

  // Dashboard Screen Styles
  dashboardContainer: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  dashboardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  dashboardHeaderIcon: {
    width: 40,
    height: 40,
    backgroundColor: '#10b981',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardHeaderIconText: {
    fontSize: 20,
  },
  dashboardHeaderText: {
    flex: 1,
  },
  dashboardHeaderTitle: {
    fontSize: 18,
    fontWeight: '400',
    color: '#111827',
    lineHeight: 28,
  },
  dashboardHeaderSubtitle: {
    fontSize: 14,
    fontWeight: '400',
    color: '#4b5563',
    lineHeight: 20,
  },

  // Chart Card
  dashboardChartCard: {
    marginHorizontal: 24,
    marginTop: 24,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  dashboardChartTitle: {
    fontSize: 18,
    color: '#111827',
    marginBottom: 24,
    textAlign: 'center',
  },
  dashboardChart: {
    height: 192,
    flexDirection: 'row',
    marginBottom: 24,
  },
  dashboardChartYAxis: {
    width: 42,
    justifyContent: 'space-between',
    paddingRight: 8,
  },
  dashboardChartYLabel: {
    fontSize: 12,
    color: '#78716c',
    textAlign: 'right',
  },
  dashboardChartArea: {
    flex: 1,
    position: 'relative',
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#e5e7eb',
  },
  dashboardMemoryLine: {
    position: 'absolute',
    top: 30,
    left: 10,
    width: 208,
    height: 3,
    backgroundColor: '#4f46e5',
  },
  dashboardAttentionLine: {
    position: 'absolute',
    top: 45,
    left: 10,
    width: 208,
    height: 3,
    backgroundColor: '#22c55e',
  },
  dashboardMemoryPoint: {
    position: 'absolute',
    width: 10,
    height: 10,
    backgroundColor: '#4f46e5',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#4f46e5',
  },
  dashboardAttentionPoint: {
    position: 'absolute',
    width: 10,
    height: 10,
    backgroundColor: '#22c55e',
    borderRadius: 5,
    borderWidth: 2,
    borderColor: '#22c55e',
  },
  dashboardChartXAxis: {
    position: 'absolute',
    bottom: -24,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  dashboardChartXLabel: {
    fontSize: 12,
    color: '#78716c',
  },

  // Legend
  dashboardLegend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 24,
    marginTop: 8,
  },
  dashboardLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dashboardMemoryDot: {
    width: 12,
    height: 12,
    backgroundColor: '#4f46e5',
    borderRadius: 6,
  },
  dashboardAttentionDot: {
    width: 12,
    height: 12,
    backgroundColor: '#22c55e',
    borderRadius: 6,
  },
  dashboardLegendText: {
    fontSize: 14,
    color: '#4b5563',
  },

  // Metric Cards
  dashboardMetrics: {
    marginHorizontal: 24,
    marginTop: 16,
    gap: 16,
  },
  dashboardMemoryCard: {
    backgroundColor: '#eef2ff',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1,
    borderColor: '#c7d2fe',
  },
  dashboardAttentionCard: {
    backgroundColor: '#f0fdf4',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  dashboardMoodCard: {
    backgroundColor: '#fefce8',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1,
    borderColor: '#fef08a',
  },
  dashboardMetricIcon: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardMemoryIconText: {
    fontSize: 32,
  },
  dashboardAttentionIconText: {
    fontSize: 32,
  },
  dashboardMoodIconText: {
    fontSize: 32,
  },
  dashboardMetricContent: {
    flex: 1,
  },
  dashboardMetricTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#111827',
    lineHeight: 24,
  },
  dashboardMetricSubtitle: {
    fontSize: 14,
    fontWeight: '400',
    color: '#4b5563',
    lineHeight: 20,
  },
  dashboardMetricStats: {
    alignItems: 'flex-end',
  },
  dashboardMetricValue: {
    fontSize: 18,
    fontWeight: '400',
    color: '#111827',
    lineHeight: 28,
  },
  dashboardMetricStable: {
    fontSize: 14,
    fontWeight: '400',
    color: '#22c55e',
    lineHeight: 20,
  },
  dashboardMetricImproved: {
    fontSize: 14,
    fontWeight: '400',
    color: '#22c55e',
    lineHeight: 20,
  },

  // Summary Card
  dashboardSummaryCard: {
    marginHorizontal: 24,
    marginTop: 16,
    marginBottom: 32,
    backgroundColor: '#d1fae5',
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  dashboardSummaryTitle: {
    fontSize: 16,
    fontWeight: '400',
    color: '#065f46',
    lineHeight: 24,
    textAlign: 'center',
    marginBottom: 8,
  },
  dashboardSummaryText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#047857',
    lineHeight: 20,
    textAlign: 'center',
  },

  keyboardView: {
    flex: 1,
  },
  messagesList: {
    padding: 16,
    flexGrow: 1,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 96,
  },
  emptyText: {
    fontSize: 16,
    color: '#64748b',
  },
  messageContainer: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 16,
    marginBottom: 12,
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#3b82f6',
  },
  aiMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  messageText: {
    fontSize: 16,
    color: '#0f172a',
  },
  userMessageText: {
    color: '#f8fafc',
  },
  timestamp: {
    fontSize: 12,
    marginTop: 4,
    opacity: 0.7,
    color: '#64748b',
  },
  userTimestamp: {
    color: '#f8fafc',
  },
  loadingContainer: {
    padding: 8,
    paddingLeft: 16,
  },
  loadingText: {
    fontSize: 14,
    color: '#64748b',
    fontStyle: 'italic',
  },
  inputContainer: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    alignItems: 'flex-end',
  },
  input: {
    flex: 1,
    backgroundColor: '#f1f5f9',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    maxHeight: 96,
    marginRight: 8,
  },
  sendButton: {
    backgroundColor: '#3b82f6',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 10,
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    backgroundColor: '#f1f5f9',
  },
  sendButtonText: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '600',
  },
});
